export default {
    "code": 1,
    "min_id": 1570525200,
    "msg": "SUCCESS",
    "data": [{
        "subject_id": "7260",
        "name": "型男魅力",
        "content": "经典永不过时$emoji表情[43]$\n超耐穿$emoji表情[55]$牛仔裤\n百搭时尚又舒适\n男神们都有一条$emoji表情[14]$还不立刻下单",
        "app_hot_image": "../../static/img/service/icon_addpic.png",
        "addtime": "1570523825",
        "activity_start_time": "1570590000",
        "activity_end_time": "1570723199",
        "share_times": "4692",
        "item_type": "1",
        "show_text": "经典永不过时<img src='../../static/img/service/icon_addpic.png' data-emoji='43'><br>超耐穿<img src='http:\/\/img.haodanku.com\/1_bqfh105.png' data-emoji='55'>牛仔裤<br>百搭时尚又舒适<br>男神们都有一条<img src='http:\/\/img.haodanku.com\/1_bqfh56.png' data-emoji='14'>还不立刻下单",
        "copy_text": "经典永不过时✨<br>超耐穿👍牛仔裤<br>百搭时尚又舒适<br>男神们都有一条😏还不立刻下单",
        "item_data": [{
            "product_id": "11392940",
            "subject_id": "7260",
            "itemid": "569397247409",
            "itemtitle": "春秋季长裤子男士牛仔裤男直筒韩版宽松潮牌休闲修身潮流秋冬2019",
            "itemshorttitle": "【战线狼2条装】春夏季新款牛仔裤",
            "itemdesc": "22万+的好评，韩版男士春夏季休闲弹力牛仔裤，不掉色，不缩水，不起球，弹力大，穿上不闷热，修身百塔，潮流时尚，多款可选，等啥呢赶紧抢！【赠运费险】",
            "itemprice": 69.8,
            "itemsale": "110579",
            "itemsale2": "649",
            "todaysale": "797",
            "itempic": "../../static/img/service/icon_addpic.png",
            "itempic_copy": "0_569397247409_1570456337.jpg",
            "itempic_type": "0",
            "fqcat": "2",
            "itemendprice": 49.8,
            "shoptype": "B",
            "couponurl": "../../static/img/service/icon_addpic.png",
            "couponstarttime": "1570464000",
            "couponendtime": "1570809599",
            "couponmoney": "20",
            "is_brand": "0",
            "is_live": "0",
            "guide_article": "22万+的好评，韩版男士春夏季休闲弹力牛仔裤，不掉色，不缩水，不起球，弹力大，穿上不闷热，修身百塔，潮流时尚，多款可选，等啥呢赶紧抢！【赠运费险】",
            "videoid": "0",
            "activity_type": "普通活动",
            "clickurl": "",
            "tkrates": 0.3,
            "son_category": "50010167",
            "activityid": null
        }, {
            "product_id": "11392944",
            "subject_id": "7260",
            "itemid": "557212998598",
            "itemtitle": "长裤男士牛仔裤男直筒宽松秋季2019加绒新款休闲秋冬款潮牌裤子男",
            "itemshorttitle": "【2条】弹力修身直筒牛仔裤子男",
            "itemdesc": "【赠运费险】超多款式可选，混纺棉柔软面料。修身直筒宽松版型。真正做到色泽稳定、抗皱、的品质工艺。品味源于品质，精心剪裁，追求产品价值。",
            "itemprice": 68,
            "itemsale": "7985",
            "itemsale2": "4",
            "todaysale": "74",
            "itempic": "http:../../static/img/service/icon_addpic.png",
            "itempic_copy": "0_557212998598_1569778433.jpg",
            "itempic_type": "0",
            "fqcat": "2",
            "itemendprice": 58,
            "shoptype": "B",
            "couponurl": "../../static/img/service/icon_addpic.png",
            "couponstarttime": "1570464000",
            "couponendtime": "1570723199",
            "couponmoney": "10",
            "is_brand": "0",
            "is_live": "0",
            "guide_article": "【赠运费险】超多款式可选，混纺棉柔软面料。修身直筒宽松版型。真正做到色泽稳定、抗皱、的品质工艺。品味源于品质，精心剪裁，追求产品价值。",
            "videoid": "0",
            "activity_type": "普通活动",
            "clickurl": "",
            "tkrates": 0.3,
            "son_category": "50010167",
            "activityid": null
        }, {
            "product_id": "11392942",
            "subject_id": "7260",
            "itemid": "575306152771",
            "itemtitle": "春秋季男士牛仔裤男宽松弹力秋冬款休闲长裤子直筒修身韩潮流潮牌",
            "itemshorttitle": "【2条】男士必备牛仔裤弹力舒适",
            "itemdesc": "【买一送一】3高弹力直筒牛仔裤，，3D立体裁剪，精选弹力优质牛仔面料，手感柔软舒适，金属拉链，质感纽扣，经典直筒修身版型，弹力不变形，舒适不紧崩，时尚大气，耐穿耐磨。【赠运费险】",
            "itemprice": 69.9,
            "itemsale": "12720",
            "itemsale2": "45",
            "todaysale": "328",
            "itempic": "../../static/img/service/icon_addpic.png",
            "itempic_copy": "0_575306152771_1569946026.jpg",
            "itempic_type": "0",
            "fqcat": "2",
            "itemendprice": 39.9,
            "shoptype": "B",
            "couponurl": "../../static/img/service/icon_addpic.png",
            "couponstarttime": "1570464000",
            "couponendtime": "1571155199",
            "couponmoney": "30",
            "is_brand": "0",
            "is_live": "0",
            "guide_article": "【买一送一】3高弹力直筒牛仔裤，，3D立体裁剪，精选弹力优质牛仔面料，手感柔软舒适，金属拉链，质感纽扣，经典直筒修身版型，弹力不变形，舒适不紧崩，时尚大气，耐穿耐磨。【赠运费险】",
            "videoid": "0",
            "activity_type": "普通活动",
            "clickurl": "",
            "tkrates": 0.2,
            "son_category": "50010167",
            "activityid": null
        }, {
            "product_id": "11392948",
            "subject_id": "7260",
            "itemid": "586895889907",
            "itemtitle": "男士纯棉牛仔裤春秋2019新款韩版休闲宽松哈伦裤潮流束脚九分裤男",
            "itemshorttitle": "春秋男士纯棉牛仔裤九分裤",
            "itemdesc": "简约修身设计，拉长腿部视觉效果，不挑身材，轻松驾驭，超有范；优质纯棉不起球不掉色超柔软，舒适贴身，不起球不变形，潮人必备！【赠运费险】",
            "itemprice": 159,
            "itemsale": "3242",
            "itemsale2": "0",
            "todaysale": "2",
            "itempic": "../../static/img/service/icon_addpic.png",
            "itempic_copy": "0_586895889907_1568090346.jpg",
            "itempic_type": "0",
            "fqcat": "2",
            "itemendprice": 59,
            "shoptype": "C",
            "couponurl": "../../static/img/service/icon_addpic.png",
            "couponstarttime": "1570464000",
            "couponendtime": "1571068799",
            "couponmoney": "100",
            "is_brand": "0",
            "is_live": "0",
            "guide_article": "简约修身设计，拉长腿部视觉效果，不挑身材，轻松驾驭，超有范；优质纯棉不起球不掉色超柔软，舒适贴身，不起球不变形，潮人必备！【赠运费险】",
            "videoid": "0",
            "activity_type": "普通活动",
            "clickurl": "",
            "tkrates": 0.3,
            "son_category": "50010167",
            "activityid": null
        },{
            "product_id": "11392947",
            "subject_id": "7260",
            "itemid": "562516270827",
            "itemtitle": "HWE秋季牛仔裤男士黑色潮牌宽松直筒长裤修身小脚裤子韩版潮流",
            "itemshorttitle": "HWE秋季潮流男士小脚牛仔裤",
            "itemdesc": "品牌保障，正品授权，精选优质运动健康面料，舒适保暖，不起球，不褪色，亲肤舒适，时尚潮流！【赠运费险】",
            "itemprice": 179,
            "itemsale": "4068",
            "itemsale2": "0",
            "todaysale": "2",
            "itempic": "https:\/\/img.alicdn.com\/bao\/uploaded\/i3\/3357915401\/O1CN01O2FDJw1plhhuPkejk_!!0-item_pic.jpg",
            "itempic_copy": "1_562516270827_1570205434.jpg",
            "itempic_type": "1",
            "fqcat": "2",
            "itemendprice": 79,
            "shoptype": "B",
            "couponurl": "http:\/\/uland.taobao.com\/quan\/detail?sellerId=3357915401&activityId=ac3bc51c15bc4e32b05d46df13e281f9",
            "couponstarttime": "1570204800",
            "couponendtime": "1570809599",
            "couponmoney": "100",
            "is_brand": "0",
            "is_live": "0",
            "guide_article": "",
            "videoid": "0",
            "activity_type": "普通活动",
            "clickurl": "",
            "tkrates": 0.2,
            "son_category": "50010167",
            "activityid": null
        }]
    }, {
        "subject_id": "7242",
        "name": "围住美丽",
        "content": "天冷到缩脖子多难看啊$emoji表情[20]$\n一条围巾又暖又美丽\n$emoji表情[80]$拍照可上镜了\n速度安排$emoji表情[292]$不惧寒潮",
        "app_hot_image": "http:\/\/img.haodanku.com\/FvyauPNI500CyO36BKQYaWKBauMk-600",
        "addtime": "1570431921",
        "activity_start_time": "1570525200",
        "activity_end_time": "1570636799",
        "share_times": "5716",
        "item_type": "1",
        "show_text": "天冷到缩脖子多难看啊<img src='http:\/\/img.haodanku.com\/1_bqfh26.png' data-emoji='20'><br>一条围巾又暖又美丽<br><img src='http:\/\/img.haodanku.com\/1_bqfh135.png' data-emoji='80'>拍照可上镜了<br>速度安排<img src='http:\/\/img.haodanku.com\/2_bqfh72.png' data-emoji='292'>不惧寒潮",
        "copy_text": "天冷到缩脖子多难看啊😰<br>一条围巾又暖又美丽<br>💁拍照可上镜了<br>速度安排🍂不惧寒潮",
        "item_data": [{
            "product_id": "11392711",
            "subject_id": "7242",
            "itemid": "598363680506",
            "itemtitle": "【拍2件第二件0元】品牌促销 反季清仓100%柔软围巾披肩加长加厚",
            "itemshorttitle": "反季清仓100%柔软围巾",
            "itemdesc": "【第二件0元】品牌促销，反季清仓100%柔软围巾披肩加长加厚，纯色围巾，多色可选，防寒时尚两不误，布料柔软舒适，不易起球。",
            "itemprice": 59.9,
            "itemsale": "282",
            "itemsale2": "0",
            "todaysale": "0",
            "itempic": "https:\/\/img.alicdn.com\/i4\/812741566\/O1CN018pqTD81NRGn1VvYYn_!!812741566.jpg",
            "itempic_copy": "0_598363680506_1570427822.jpg",
            "itempic_type": "0",
            "fqcat": "5",
            "itemendprice": 34.9,
            "shoptype": "C",
            "couponurl": "https:\/\/uland.taobao.com\/quan\/detail?sellerId=812741566&activityId=eae8f2cd3db14bd98cb0c351ff8a2960",
            "couponstarttime": "1570377600",
            "couponendtime": "1570723199",
            "couponmoney": "25",
            "is_brand": "0",
            "is_live": "0",
            "guide_article": "【第二件0元】品牌促销，反季清仓100%柔软围巾披肩加长加厚，纯色围巾，多色可选，防寒时尚两不误，布料柔软舒适，不易起球。",
            "videoid": "233379822995",
            "activity_type": "普通活动",
            "clickurl": "",
            "tkrates": 0.3011,
            "son_category": "50007003",
            "activityid": null
        }, {
            "product_id": "11392694",
            "subject_id": "7242",
            "itemid": "537826984121",
            "itemtitle": "格子围巾女秋冬季韩版百搭日系原宿风男学生可爱软妹ins少女围脖",
            "itemshorttitle": "韩版加厚加长经典格子围巾",
            "itemdesc": "戴腻了纯色拼色围巾，今日就给你带来不一样的--经典时尚格子围巾，不一样的时尚与个性，柔软舒适面料，加厚加长，戴着灰常暖和！围巾披肩两用，轻松御寒，日系少女软妹必备哟~【赠运费险】",
            "itemprice": 19.8,
            "itemsale": "7725",
            "itemsale2": "52",
            "todaysale": "215",
            "itempic": "https:\/\/img.alicdn.com\/imgextra\/i2\/1075748776\/O1CN01MHDfFV2EhSR3p32Hb_!!1075748776.jpg",
            "itempic_copy": "0_537826984121_1569940483.jpg",
            "itempic_type": "0",
            "fqcat": "5",
            "itemendprice": 9.8,
            "shoptype": "B",
            "couponurl": "https:\/\/uland.taobao.com\/quan\/detail?sellerId=2908675478&activityId=b582360f9e1f47e9aa5559218fd0ebc6",
            "couponstarttime": "1569945600",
            "couponendtime": "1570550399",
            "couponmoney": "10",
            "is_brand": "0",
            "is_live": "0",
            "guide_article": "戴腻了纯色拼色围巾，今日就给你带来不一样的--经典时尚格子围巾，不一样的时尚与个性，柔软舒适面料，加厚加长，戴着灰常暖和！围巾披肩两用，轻松御寒，日系少女软妹必备哟~【赠运费险】",
            "videoid": "0",
            "activity_type": "普通活动",
            "clickurl": "",
            "tkrates": 0.2,
            "son_category": "50007003",
            "activityid": null
        }, {
            "product_id": "11392714",
            "subject_id": "7242",
            "itemid": "602995402208",
            "itemtitle": "情人棉织围巾毛线团男宝宝牛奶棉粗毛线女手工编织针织diy 围巾线",
            "itemshorttitle": "情人棉织手工编织针织diy围巾线",
            "itemdesc": "亲肤柔软，触感好，颜色饱满，质感。保暖性强，不起球不褪色，多色可选，带你感受编织的乐趣！！！",
            "itemprice": 32,
            "itemsale": "38",
            "itemsale2": "0",
            "todaysale": "0",
            "itempic": "http:\/\/img.alicdn.com\/imgextra\/i1\/2149613608\/O1CN01TvUEjP1cWVYrzL5pF_!!2149613608.jpg",
            "itempic_copy": "0_602995402208_1569741839.jpg",
            "itempic_type": "0",
            "fqcat": "5",
            "itemendprice": 22,
            "shoptype": "B",
            "couponurl": "https:\/\/uland.taobao.com\/quan\/detail?sellerId=2149613608&activityId=b72ee91550cb407db04d8cd5083e69ac",
            "couponstarttime": "1569686400",
            "couponendtime": "1570550399",
            "couponmoney": "10",
            "is_brand": "0",
            "is_live": "0",
            "guide_article": "亲肤柔软，触感好，颜色饱满，质感。保暖性强，不起球不褪色，多色可选，带你感受编织的乐趣！！！",
            "videoid": "0",
            "activity_type": "普通活动",
            "clickurl": "",
            "tkrates": 0.2,
            "son_category": "50009039",
            "activityid": null
        }]
    }]
}